trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Checkout
    jobs:
      - job: CheckoutCode
        steps:
          - checkout: self

  - stage: Build
    jobs:

      - job: BuildFrontend
        steps:
          - script: |
              sh ./BuildFrontend.sh
            displayName: 'Run Build Frontend Stage'

      - job: BuildBackend
        steps:
          - script: |
              sh ./BuildBackend.sh
            displayName: 'Run Build Backend Stage'

  - stage: Test
    jobs:

      - job: TestFrontend
        dependsOn: BuildFrontend
        steps:
          - script: |
              sh ./TestFrontend.sh
            displayName: 'Run Test Frontend Stage'

      - job: TestBackend
        dependsOn: BuildBackend
        steps:
          - script: |
              sh ./TestBackend.sh
            displayName: 'Run Test Backend Stage'

  - stage: Package
    dependsOn: Test
    jobs:

      - job: PackageFrontend
        steps:
          - script: |
              sh ./PackageFrontend.sh
            displayName: 'Run Package Frontend Stage'

      - job: PackageBackend
        steps:
          - script: |
              sh ./PackageBackend.sh
            displayName: 'Run Package Backend Stage'

  - stage: Deploy
    dependsOn: Package
    jobs:
      - job: Deploy
        steps:
          - script: |
              sh ./Deploy.sh
            displayName: 'Run Deploy Stage'

  - stage: APITests
    dependsOn: Deploy
    jobs:
      - job: RunAPITests
        steps:
          - script: |
              sh ./APITests.sh
            displayName: 'Run API Tests Stage'

  - stage: UITests
    dependsOn: APITests
    jobs:
      - job: RunUITests
        steps:
          - script: |
              sh ./UITests.sh
            displayName: 'Run UI Tests Stage'
