trigger:
  - main

pool:
  vmImage: "ubuntu-latest"
  
stages:
  - stage: Checkout
    jobs:
      - job: CheckoutCode
        steps:
          - checkout: self

  - stage: Deploy
    dependsOn: Checkout
    jobs:
      - job: Deploy
        steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
          displayName: 'Terraform : azurerm'
          inputs:
            workingDirectory: IAC
            backendAzureRmUseEnvironmentVariablesForAuthentication: false
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: AzureCloud
            backendAzureRmResourceGroupName: AISDLC
            backendAzureRmStorageAccountName: aistatefile
            backendAzureRmContainerName: statefile
            backendAzureRmKey: terraform.tfstate
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
          displayName: 'Import Disk Attachment Resource'
          inputs:
            command: custom
            customCommand: import 'azurerm_virtual_machine_data_disk_attachment.disk_attachment' '/subscriptions/434d9ccf-0fbf-4203-a25a-314f7650f6f7/resourceGroups/AISDLC/providers/Microsoft.Compute/virtualMachines/SDLC-vm/dataDisks/AI-SDLC-Database'
            environmentServiceNameAzureRM: AzureCloud
            backendAzureRmUseEnvironmentVariablesForAuthentication: false
            backendAzureRmUseEntraIdForAuthentication: false
            workingDirectory: 'IAC'
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
          displayName: 'Terraform : azurerm'
          inputs:
            command: apply
            workingDirectory: IAC
            environmentServiceNameAzureRM: AzureCloud
            backendAzureRmUseEnvironmentVariablesForAuthentication: false
            backendAzureRmUseEntraIdForAuthentication: false   
  - stage: Build
    dependsOn: Deploy
    jobs:
      - job: Build
        steps:
          - task: Gradle@3
            inputs:
              gradleVersion: 'latest'

          - task: Gradle@3
            inputs:
              projectFile: 'backend/build.gradle'
              tasks: 'war'
              codeCoverageToolOption: 'JaCoCo'
              codeCoverageClassFilter: '+:com.example.backend.*'
              codeCoverageClassFilesDirectories: 'backend/src/main/java'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              publishJavaCodeCoverageResults: true
          
          # Build frontend using Node.js
          - task: NodeTool@0
            inputs:
              nodeVersion: '14.x'
          
          - task: Npm@1
            inputs:
              workingDir: 'frontend'
          
          - task: Npm@1
            inputs:
              workingDir: 'frontend'
              command: 'run build'
          
          - task: CopyFiles@2
            inputs:
              contents: 'frontend/dist/**'
              targetFolder: '$(build.artifactStagingDirectory)'
          # Copy artifacts to Tomcat webapps folder
          - task: CopyFiles@2
            inputs:
              contents: '**/target/*.war'
              targetFolder: '/opt/tomcat/webapps'
              overWrite: true
              flattenFolders: true
              hostName: '$(vm-hostname)'
              username: '$(vm-username)'
              password: '$(vm-password)'
      
  - stage: APITests
    dependsOn: Deploy
    jobs:
      - job: RunAPITests
        steps:
          - script: |
              chmod +x ./scripts/run-api-tests.sh
              sh ./scripts/run-api-tests.sh
            displayName: "Run API Tests Stage"
          - task: PublishPipelineArtifact@1
            displayName: "Publish API test results"
            condition: always()
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/artifacts
              artifactName: api-test-results
              artifactType: PipelineArtifact

  - stage: UITests
    dependsOn: APITests
    jobs:
      - job: RunUITests
        steps:
          - script: |
              chmod +x ./scripts/run-ui-tests.sh
              sh ./scripts/run-ui-tests.sh
            displayName: "Run UI Tests Stage"
          - task: PublishPipelineArtifact@1
            displayName: "Publish UI test results"
            condition: always()
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/artifacts
              artifactName: ui-test-results
              artifactType: PipelineArtifact
