trigger:
  - main

pool:
  vmImage: "ubuntu-latest"
  
stages:
  - stage: Checkout
    jobs:
      - job: CheckoutCode
        steps:
          - checkout: self

  - stage: Deploy
    dependsOn: Checkout
    jobs:
      - job: Deploy
        steps:
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
          displayName: 'Terraform : azurerm'
          inputs:
            workingDirectory: IAC
            backendAzureRmUseEnvironmentVariablesForAuthentication: false
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: AzureCloud
            backendAzureRmResourceGroupName: AISDLC
            backendAzureRmStorageAccountName: aistatefile
            backendAzureRmContainerName: statefile
            backendAzureRmKey: terraform.tfstate
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
          displayName: 'Terraform : azurerm'
          inputs:
            command: apply
            workingDirectory: IAC
            environmentServiceNameAzureRM: AzureCloud
            backendAzureRmUseEnvironmentVariablesForAuthentication: false
            backendAzureRmUseEntraIdForAuthentication: false   
  - stage: Build
    dependsOn: Checkout
    jobs:
      - job: Build
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Updating apt repository..."
                sudo apt-get update -y
                
                echo "Installing OpenJDK 17..."
                sudo apt-get install -y openjdk-17-jdk
                
                echo "Setting JAVA_HOME..."
                sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
                sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          
          - task: Gradle@3
            inputs:
              gradleWrapperFile: backend/gradlew
              workingDirectory: backend
              tasks: 'clean build'
              javaHomeOption: 'JDKPath'
              jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                cd backend
                ll
          
#          # Build frontend using Node.js
#          - task: NodeTool@0
#            inputs:
#              nodeVersion: '14.x'
#
#          - task: Npm@1
#            inputs:
#              workingDir: 'frontend'
#
#          - task: Npm@1
#            inputs:
#              workingDir: 'frontend'
#              command: 'run build'
#
#          - task: CopyFiles@2
#            inputs:
#              contents: 'frontend/dist/**'
#              targetFolder: '$(build.artifactStagingDirectory)'
#          # Copy artifacts to Tomcat webapps folder
#          - task: CopyFiles@2
#            inputs:
#              contents: '**/target/*.war'
#              targetFolder: '/opt/tomcat/webapps'
#              overWrite: true
#              flattenFolders: true
#              hostName: '$(vm-hostname)'
#              username: '$(vm-username)'
#              password: '$(vm-password)'
      
  - stage: APITests
    dependsOn: Build
    jobs:
      - job: RunAPITests
        steps:
          - script: |
              chmod +x ./scripts/run-api-tests.sh
              sh ./scripts/run-api-tests.sh
            displayName: "Run API Tests Stage"
          - task: PublishPipelineArtifact@1
            displayName: "Publish API test results"
            condition: always()
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/artifacts
              artifactName: api-test-results
              artifactType: PipelineArtifact

  - stage: UITests
    dependsOn: APITests
    jobs:
      - job: RunUITests
        steps:
          - script: |
              chmod +x ./scripts/run-ui-tests.sh
              sh ./scripts/run-ui-tests.sh
            displayName: "Run UI Tests Stage"
          - task: PublishPipelineArtifact@1
            displayName: "Publish UI test results"
            condition: always()
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/artifacts
              artifactName: ui-test-results
              artifactType: PipelineArtifact
