openapi: 3.0.0
info:
  title: Recruitment API
  version: 1.0.0
paths:
  /api/recruiters/add:
    post:
      summary: Add a new recruiter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                FirstName:
                  type: string
                LastName:
                  type: string
                Email:
                  type: string
                PhoneNumber:
                  type: integer
      responses:
        '201':
          description: Created
        '400':
          description: Bad request

  /api/recruiters/getAll:
    get:
      summary: Get all recruiters
      responses:
        '200':
          description: A list of recruiters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recruiter'
  /api/recruiters/{RecruiterID}:
    get:
      summary: Get a recruiter by ID
      parameters:
        - in: path
          name: RecruiterID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single recruiter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recruiter'
        '404':
          description: Not found

  /api/vacancy/add:
    post:
      summary: Add a new vacancy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                JobTitle:
                  type: string
                Description:
                  type: string
                Requirements:
                  type: string
                Location:
                  type: string
                MaxSalary:
                  type: number
                ApplicationDeadline:
                  type: string
                  format: date-time
                CreatedBy:
                  type: integer
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
  /api/vacancy/getAll:
    get:
      summary: Get all vacancies
      responses:
        '200':
          description: A list of vacancies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vacancy'
  /api/vacancy/{VacancyID}:
    get:
      summary: Get a vacancy by ID
      parameters:
        - in: path
          name: VacancyID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single vacancy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vacancy'
        '404':
          description: Not found
components:
  schemas:
    Recruiter:
      type: object
      properties:
        RecruiterID:
          type: integer
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          type: string
        PhoneNumber:
          type: integer
        CreationDate:
          type: string
          format: date-time
    Vacancy:
      type: object
      properties:
        VacancyID:
          type: string
        JobTitle:
          type: string
        Description:
          type: string
        Requirements:
          type: string
        Location:
          type: string
        MaxSalary:
          type: number
        ApplicationDeadline:
          type: string
          format: date-time
        CreatedBy:
          type: integer