openapi: 3.0.0
info:
  title: Recruitment API
  version: 1.0.0
paths:
  /api/vacancies:
    get:
      summary: Get all vacancies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VacancyResponse'
    post:
      summary: Add a new vacancy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVacancyRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateVacancyResponse'
        '400':
          description: Bad request
  /api/vacancies/{vacancyId}:
    get:
      summary: Get a specific vacancy by ID
      parameters:
        - in: path
          name: vacancyId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VacancyResponse'
        '404':
          description: Not Found

components:
  schemas:
    VacancyResponse:
      type: object
      properties:
        vacancyId:
          type: string
          example: JOB000001
        jobTitle:
          type: string
          example: Developer
        description:
          type: string
          example: Looking for a Java developer
        requirements:
          type: string
          example: Must be having hands experience in Java
        location:
          type: string
          example: Bangalore
        maxSalary:
          type: number
          format: float
          example: 10000000.23
        applicationDeadline:
          type: string
          format: date-time
          example: 2024-12-31T23:59:59
        createdBy:
          type: string
          example: "john.doe@devon.nl"

    CreateVacancyRequest:
      type: object
      required:
        - jobTitle
        - description
        - requirements
        - location
        - maxSalary
        - applicationDeadline
        - createdBy
      properties:
        jobTitle:
          type: string
          example: Developer
        description:
          type: string
          example: Looking for a Java developer
        requirements:
          type: string
          example: Must be having hands-on experience in Java
        location:
          type: string
          example: Bangalore
        maxSalary:
          type: number
          format: float
          example: 10000000.23
        applicationDeadline:
          type: string
          format: date-time
          example: 2024-12-31T23:59:59
        createdBy:
          type: string
          example: "john.doe@devon.nl"

    CreateVacancyResponse:
      type: object
      properties:
        vacancyId:
          type: string
          example: JOB000001