spring:
  datasource:
    #url: jdbc:sqlite:recruitment.db
    url: jdbc:sqlite:/opt/tomcat/logs/recruitment.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      hb2ddl.auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

configuration :
  defaultJobId: JOB000001
  formatJobId : JOB%06d
  dateTimeFormat: yyyy-MM-dd HH:mm:ss

server:
  port : 8080