spring:
  datasource:
    url: jdbc:sqlite:backend/recruitment.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      hb2ddl.auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false

configuration :
  defaultJobId: JOB00001
  formatJobId : JOB%06d

server:
  port : 8091